### ISSUE TITLE
Allow local schema resolution

### ISSUE THREAD

**Issue by aexvir** [kiwicom/schemathesis#294]
Schemathesis works fine when the schema is available from the server, but that's not always desired, and the possibility to specify a base URL and a local schema file seems the best choice for environments like CI systems.

The problem is... that `schemathesis` expects the complete schema to be passed, which is not always available (think of CI where the projects have the schema split in multiple files and references), which makes it hard to be used in those cases.

Personally I've used [`prance`](https://github.com/jfinkhaeuser/prance) for parsing the schemas, as it allows schema resolution. The only drawback that I see is the dependency on `pyicu`, which might be annoying to set up for local development, although it's optional, but I found it necessary for some cases.

If you are fine with adding support for this type of schema, and increasing the projects' complexity a bit by adding it, I'm ok with picking it up and sending a PR

**Comment by Stranger6667** [comment]
Could you, please, share an example of such a schema layout? Especially the part with references to different files

**Comment by aexvir** [comment]
Something like this...

```yaml
openapi: 3.0.2

info:
  title: Some API
  description: An API for stuff
  version: 0.1.0
  x-visibility: unlisted

paths:
  /ancillaries/offers/check:
    $ref: "paths/ancillaries.yaml#/AncillariesOffersCheckPath"
  /ping:
    $ref: "../../openapi/openapi/paths/simple.yaml#/PingPath"

tags:
  - name: ancillaries
    description: Operations related to ancillaries.
```

**Comment by aexvir** [comment]
That causes the following exception in `schemathesis`

```bash
========================================================================================== Schemathesis test session starts =========================================================================================
platform Darwin -- Python 3.7.5, schemathesis-0.16.0, hypothesis-4.39.0, hypothesis_jsonschema-0.9.8, jsonschema-3.0.2
rootdir: /Users/alexviscreanu/Projects/schemathesis
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/alexviscreanu/Projects/schemathesis/.hypothesis/examples')
Schema location: ../backend/kw/pub/openapi/openapi.yaml
Base URL: http://localhost
Specification version: Open API 3.0.2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/alexviscreanu/Library/Caches/pypoetry/virtualenvs/schemathesis-SoLs9ad5-py3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alexviscreanu/Library/Caches/pypoetry/virtualenvs/schemathesis-SoLs9ad5-py3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/alexviscreanu/Library/Caches/pypoetry/virtualenvs/schemathesis-SoLs9ad5-py3.7/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alexviscreanu/Library/Caches/pypoetry/virtualenvs/schemathesis-SoLs9ad5-py3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alexviscreanu/Library/Caches/pypoetry/virtualenvs/schemathesis-SoLs9ad5-py3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/alexviscreanu/Projects/schemathesis/src/schemathesis/cli/__init__.py", line 158, in run
    execute(prepared_runner)
  File "/Users/alexviscreanu/Projects/schemathesis/src/schemathesis/cli/__init__.py", line 197, in execute
    output.handle_event(context, event)
  File "/Users/alexviscreanu/Projects/schemathesis/src/schemathesis/cli/output.py", line 271, in handle_event
    handle_initialized(context, event)
  File "/Users/alexviscreanu/Projects/schemathesis/src/schemathesis/cli/output.py", line 61, in handle_initialized
    click.secho(f"collected endpoints: {event.schema.endpoints_count}", bold=True)
  File "/Users/alexviscreanu/Projects/schemathesis/src/schemathesis/schemas.py", line 74, in endpoints_count
    return len(list(self.get_all_endpoints()))
  File "/Users/alexviscreanu/Projects/schemathesis/src/schemathesis/schemas.py", line 148, in get_all_endpoints
    or should_skip_by_tag(definition.get("tags"), self.tag)
AttributeError: 'str' object has no attribute 'get'
```

Because `definition` is equals to `paths/ancillaries.yaml#/AncillariesOffersCheckPath`

**Comment by Stranger6667** [comment]
Done in 319ff91

**Comment by Stranger6667** [comment]
Thank you @aexvir for bringing this :)
