### ISSUE TITLE
Hypothesis deadline can not be set to `None` from command line

### ISSUE THREAD

**Issue by jamescooke** [kiwicom/schemathesis#349]
When testing against an unreliable API by calling Schemathesis from the command line, I'm receiving the following warning:

```
Unreliable test timings! On an initial run, this test took 797.46ms, which exceeded the deadline of 500.00ms, but on a subsequent run it took 166.09 ms, which did not. If you expect this sort of variability in your test timings, consider turning deadlines off for this test by setting deadline=None.
```

But when invoking Schemathesis with `--hypothesis-deadline=None` in order to disable deadlines, an error is returned (this is on master at https://github.com/kiwicom/schemathesis/commit/bea1f725681b857e301729cec7d1bcff245dab3e):

```
$ schemathesis run https://petstore3.swagger.io/api/v3/openapi.json --hypothesis-deadline=None                                                                           
Usage: schemathesis run [OPTIONS] SCHEMA
Try "schemathesis run -h" for help.

Error: Invalid value for "--hypothesis-deadline": None is not a valid integer
```

Having a guess and setting `--hypothesis-deadline=0` raises an exception:

```
$ schemathesis run https://petstore3.swagger.io/api/v3/openapi.json --hypothesis-deadline=0
Traceback (most recent call last):
  File "/home/james/active/schemathesis/venv/bin/schemathesis", line 11, in <module>
    load_entry_point('schemathesis', 'console_scripts', 'schemathesis')()
  File "/home/james/active/schemathesis/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/james/active/schemathesis/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/james/active/schemathesis/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/james/active/schemathesis/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/james/active/schemathesis/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/james/active/schemathesis/src/schemathesis/cli/__init__.py", line 183, in run
    execute(prepared_runner, workers_num)
  File "/home/james/active/schemathesis/src/schemathesis/cli/__init__.py", line 234, in execute
    for event in prepared_runner:
  File "/home/james/active/schemathesis/src/schemathesis/runner/__init__.py", line 332, in execute_from_schema
    request_timeout=request_timeout,
  File "<attrs generated init schemathesis.runner.SingleThreadRunner>", line 4, in __init__
  File "/home/james/active/schemathesis/src/schemathesis/runner/__init__.py", line 34, in get_hypothesis_settings
    settings = hypothesis.settings(settings, **hypothesis_options)
  File "/home/james/active/schemathesis/venv/lib/python3.7/site-packages/hypothesis/_settings.py", line 182, in __init__
    kwargs[setting.name] = setting.validator(kwargs[setting.name])
  File "/home/james/active/schemathesis/venv/lib/python3.7/site-packages/hypothesis/_settings.py", line 676, in _validate_deadline
    "deadline <= 0. Use deadline=None to disable deadlines." % (x,)
hypothesis.errors.InvalidArgument: deadline=timedelta(milliseconds=0) is invalid, because it is impossible to meet a deadline <= 0. Use deadline=None to disable deadlines.
```

**Comment by Stranger6667** [comment]
Hello @jamescooke !
Thank you for reporting this :) We can add a special case to the CLI parameters, sure.
Also, could you, please, try to add `--hypothesis-suppress-health-check=too_slow` to your call?  It might solve the problem itself (at least we are using it from time to time with our apps)

**Comment by Stranger6667** [comment]
I checked my own suggestion from the comment above and it is not actually what can help - it relates only to the data generation phase, not to execution. I'll work on the possibility to use `None` as a value for `deadline`

**Comment by Stranger6667** [comment]
Now Schemathesis supports a special "None" value in CLI - released in `0.22.0`  (https://pypi.org/project/schemathesis/0.22.0/)

**Comment by jamescooke** [comment]
Cool - thanks for responding so quickly. I'll try it out on Monday :+1:

**Comment by jamescooke** [comment]
Thanks for this fix - it's working well now with `--hypothesis-deadline=None`
