### ISSUE TITLE
Getting AttributeError when running schemathesis 

### ISSUE THREAD

**Issue by gauravve** [kiwicom/schemathesis#587]
Hello, 

I am getting the following error when running 

```
schemathesis run --help

Traceback (most recent call last):
  File "/Users/p728408/homebrew/bin/schemathesis", line 5, in <module>
    from schemathesis.cli import schemathesis
  File "/Users/p728408/homebrew/lib/python3.7/site-packages/schemathesis/__init__.py", line 2, in <module>
    from ._hypothesis import init_default_strategies, register_string_format
  File "/Users/p728408/homebrew/lib/python3.7/site-packages/schemathesis/_hypothesis.py", line 12, in <module>
    from hypothesis_jsonschema import from_schema
  File "/Users/p728408/homebrew/lib/python3.7/site-packages/hypothesis_jsonschema/__init__.py", line 9, in <module>
    from ._from_schema import from_schema
  File "/Users/p728408/homebrew/lib/python3.7/site-packages/hypothesis_jsonschema/_from_schema.py", line 299, in <module>
    "ipv4": st.ip_addresses(v=4).map(str),
AttributeError: module 'hypothesis.strategies' has no attribute 'ip_addresses'
```

Not able to use schemathesis. Any clues on what could be going wrong?

**Comment by gauravve** [comment]
I have fixed it thanks. Something wrong with my installation of Python. Virtualenv fixed it.

**Comment by Stranger6667** [comment]
Hi! Yep, it is likely caused by installed Hypothesis version
